# Generated by Django 4.1.3 on 2022-12-28 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='category',
            field=models.ForeignKey(default='Без категории', on_delete=django.db.models.deletion.DO_NOTHING, to='foto.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='voices',
            field=models.ManyToManyField(blank=True, related_name='foto_voices', to=settings.AUTH_USER_MODEL, verbose_name='Голоса'),
        ),
    ]
