# Generated by Django 4.1.3 on 2022-12-26 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='count',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='text',
        ),
        migrations.RemoveField(
            model_name='voices',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='voices',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='voices',
            name='user',
        ),
        migrations.RemoveField(
            model_name='foto',
            name='voices',
        ),
        migrations.AddField(
            model_name='foto',
            name='voices',
            field=models.ManyToManyField(related_name='foto_voices', to=settings.AUTH_USER_MODEL),
        ),
    ]
