# Generated by Django 4.1.3 on 2022-12-23 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0002_alter_foto_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foto.category', verbose_name='Категория'),
        ),
    ]
