# Generated by Django 4.1.3 on 2022-12-26 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foto', '0002_remove_comments_count_remove_comments_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto',
            name='comments',
        ),
        migrations.AlterField(
            model_name='foto',
            name='images',
            field=models.ImageField(upload_to='media', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='voices',
            field=models.ManyToManyField(related_name='foto_voices', to=settings.AUTH_USER_MODEL, verbose_name='Голоса'),
        ),
        migrations.AddField(
            model_name='foto',
            name='comments',
            field=models.ManyToManyField(related_name='foto_comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментарии'),
        ),
    ]
