# Generated by Django 4.1.3 on 2023-01-07 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0002_comments_approved_alter_foto_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='foto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='foto.foto', verbose_name='Фото комментария'),
        ),
    ]
