# Generated by Django 4.1.3 on 2022-12-27 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foto', '0003_remove_foto_comments_alter_foto_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='foto_comments', to=settings.AUTH_USER_MODEL, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='voices',
            field=models.ManyToManyField(blank=True, null=True, related_name='foto_voices', to=settings.AUTH_USER_MODEL, verbose_name='Голоса'),
        ),
    ]
