# Generated by Django 4.1.3 on 2023-01-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0004_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
