# Generated by Django 4.1.5 on 2023-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0005_alter_subscribe_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Удалено'),
        ),
    ]
