# Generated by Django 4.1.5 on 2023-01-16 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0008_userapikey_delete_fotoapikey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
