# Generated by Django 4.1.5 on 2023-01-26 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foto', '0010_foto_dismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='affected',
            field=models.BooleanField(default=False, verbose_name='Одобрено'),
        ),
        migrations.CreateModel(
            name='CommentsSecondLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')),
                ('approved', models.BooleanField(default=False, verbose_name='Одобрено модератором')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foto.comments', verbose_name='Первый комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
